# fly.toml app configuration file generated for orbitalone-tile-proxy-rust on 2025-05-15T21:13:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'orbitalone-tile-proxy-rust'
primary_region = 'fra'

[build]

[env]
  PORT = '8080'
  TILE_STORAGE_PATH = '/data/tiles'

[[mounts]]
  source = "tile_cache"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
