# fly.toml app configuration file generated for orbitalone-backend on 2025-04-22T21:11:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'orbitalone-backend'
primary_region = 'fra'

[build]
[build.args]
GO_VERSION = '1.24.2'

[env]
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'

[mounts]
source = "feeds_data"
destination = "/data"
